# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(890, 563)
        Dialog.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid blue;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"border:2px solid blue;\n"
"}\n"
"QGroupBox{\n"
"border:2px solid black\n"
"}\n"
"QDialog{\n"
"    background-color: rgb(0, 170, 255);\n"
"\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 10, 121, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 10, 121, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 10, 121, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(610, 10, 121, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(760, 10, 121, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 871, 471))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 851, 451))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 831, 431))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/Home.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnSenac = QtWidgets.QPushButton(self.page)
        self.btnSenac.setGeometry(QtCore.QRect(350, 300, 261, 141))
        self.btnSenac.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSenac.setStyleSheet("border:none;\n"
"background-color: none;")
        self.btnSenac.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/images-removebg-preview (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSenac.setIcon(icon)
        self.btnSenac.setIconSize(QtCore.QSize(300, 300))
        self.btnSenac.setObjectName("btnSenac")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 831, 431))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("imagens/colorful3.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 20, 391, 421))
        self.groupBox_5.setStyleSheet("color:blue;\n"
"font-size:14pt;\n"
"border:1px solid blue;\n"
"background-color:transparent;")
        self.groupBox_5.setObjectName("groupBox_5")
        self.txtValorBruto = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtValorBruto.setGeometry(QtCore.QRect(20, 130, 361, 41))
        self.txtValorBruto.setStyleSheet("color:black;")
        self.txtValorBruto.setObjectName("txtValorBruto")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 330, 171, 61))
        self.lineEdit_8.setStyleSheet("color:black;\n"
"border:none;\n"
"font-size:14pt;")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setPlaceholderText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.btnPdf = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPdf.setGeometry(QtCore.QRect(280, 180, 101, 51))
        self.btnPdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPdf.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid blue;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:blue;\n"
"border:2px solid blue;\n"
"color:white;\n"
"}")
        self.btnPdf.setObjectName("btnPdf")
        self.btnExcell = QtWidgets.QPushButton(self.groupBox_5)
        self.btnExcell.setGeometry(QtCore.QRect(150, 260, 101, 51))
        self.btnExcell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExcell.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid blue;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:blue;\n"
"border:2px solid blue;\n"
"color:white;\n"
"}")
        self.btnExcell.setObjectName("btnExcell")
        self.btnCalcular = QtWidgets.QPushButton(self.groupBox_5)
        self.btnCalcular.setGeometry(QtCore.QRect(20, 180, 101, 51))
        self.btnCalcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalcular.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid blue;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:blue;\n"
"border:2px solid blue;\n"
"color:white;\n"
"}")
        self.btnCalcular.setObjectName("btnCalcular")
        self.txtNome = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtNome.setGeometry(QtCore.QRect(20, 30, 361, 41))
        self.txtNome.setStyleSheet("color:black;")
        self.txtNome.setObjectName("txtNome")
        self.txtCargo = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtCargo.setGeometry(QtCore.QRect(20, 80, 361, 41))
        self.txtCargo.setStyleSheet("color:black;")
        self.txtCargo.setObjectName("txtCargo")
        self.btnNovo = QtWidgets.QPushButton(self.groupBox_5)
        self.btnNovo.setGeometry(QtCore.QRect(150, 180, 101, 51))
        self.btnNovo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNovo.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid blue;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:blue;\n"
"border:2px solid blue;\n"
"color:white;\n"
"}")
        self.btnNovo.setObjectName("btnNovo")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 131, 61))
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setObjectName("label_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 20, 391, 411))
        self.groupBox_4.setStyleSheet("color:blue;\n"
"font-size:14pt;\n"
"border:1px solid blue;\n"
"background-color:transparent;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtINSS = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtINSS.setGeometry(QtCore.QRect(10, 50, 341, 41))
        self.txtINSS.setStyleSheet("color:black;")
        self.txtINSS.setObjectName("txtINSS")
        self.txtFGTS = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtFGTS.setGeometry(QtCore.QRect(10, 120, 341, 41))
        self.txtFGTS.setStyleSheet("color:black;")
        self.txtFGTS.setObjectName("txtFGTS")
        self.txtIRFF = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtIRFF.setGeometry(QtCore.QRect(10, 190, 341, 41))
        self.txtIRFF.setStyleSheet("color:black;")
        self.txtIRFF.setObjectName("txtIRFF")
        self.txtValeT = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtValeT.setGeometry(QtCore.QRect(10, 260, 341, 41))
        self.txtValeT.setStyleSheet("color:black;")
        self.txtValeT.setObjectName("txtValeT")
        self.txtValeA = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtValeA.setGeometry(QtCore.QRect(10, 340, 341, 41))
        self.txtValeA.setStyleSheet("color:black;")
        self.txtValeA.setObjectName("txtValeA")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 51, 31))
        self.label_13.setStyleSheet("color:black;\n"
"border:none;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_14.setStyleSheet("color:black;\n"
"border:none;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 51, 31))
        self.label_15.setStyleSheet("color:black;\n"
"border:none;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 230, 141, 31))
        self.label_16.setStyleSheet("color:black;\n"
"border:none;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 310, 151, 31))
        self.label_17.setStyleSheet("color:black;\n"
"border:none;")
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 831, 441))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("imagens/colorful3.jpg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(360, 20, 141, 51))
        self.label_19.setStyleSheet("background-color:none;\n"
"color:black;")
        self.label_19.setObjectName("label_19")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 381, 351))
        self.groupBox_2.setStyleSheet("background-color: none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagens/inssVerdadeiro.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.txtINSS2 = QtWidgets.QLineEdit(self.page_3)
        self.txtINSS2.setGeometry(QtCore.QRect(480, 150, 261, 51))
        self.txtINSS2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid black;\n"
"border-radius:18px;")
        self.txtINSS2.setObjectName("txtINSS2")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(440, 220, 381, 91))
        self.label_20.setStyleSheet("background-color:none;\n"
"font-size:14pt;")
        self.label_20.setObjectName("label_20")
        self.lblRespostaINSS = QtWidgets.QLabel(self.page_3)
        self.lblRespostaINSS.setGeometry(QtCore.QRect(540, 320, 171, 51))
        self.lblRespostaINSS.setStyleSheet("font-size:16pt;\n"
"background-color:none;")
        self.lblRespostaINSS.setObjectName("lblRespostaINSS")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_22 = QtWidgets.QLabel(self.page_4)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 831, 431))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("imagens/colorful3.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_4)
        self.label_23.setGeometry(QtCore.QRect(360, 20, 141, 51))
        self.label_23.setStyleSheet("background-color:none;")
        self.label_23.setObjectName("label_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 80, 381, 351))
        self.groupBox_3.setStyleSheet("background-color: none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("imagens/irrfVerdadeito.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.txtIRRF2 = QtWidgets.QLineEdit(self.page_4)
        self.txtIRRF2.setGeometry(QtCore.QRect(480, 150, 261, 51))
        self.txtIRRF2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid black;\n"
"border-radius:18px;")
        self.txtIRRF2.setObjectName("txtIRRF2")
        self.label_24 = QtWidgets.QLabel(self.page_4)
        self.label_24.setGeometry(QtCore.QRect(440, 220, 381, 91))
        self.label_24.setStyleSheet("background-color:none;\n"
"font-size:14pt;")
        self.label_24.setObjectName("label_24")
        self.lblRespostaIRRF = QtWidgets.QLabel(self.page_4)
        self.lblRespostaIRRF.setGeometry(QtCore.QRect(540, 320, 171, 51))
        self.lblRespostaIRRF.setStyleSheet("font-size:16pt;\n"
"background-color:none;")
        self.lblRespostaIRRF.setObjectName("lblRespostaIRRF")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_26 = QtWidgets.QLabel(self.page_5)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 831, 431))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("imagens/colorful3.jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_5)
        self.label_27.setGeometry(QtCore.QRect(360, 20, 141, 51))
        self.label_27.setStyleSheet("background-color:none;")
        self.label_27.setObjectName("label_27")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 80, 381, 351))
        self.groupBox_6.setStyleSheet("background-color: none;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("imagens/inss.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.txtVales2 = QtWidgets.QLineEdit(self.page_5)
        self.txtVales2.setGeometry(QtCore.QRect(460, 150, 311, 41))
        self.txtVales2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid black;\n"
"border-radius:18px;")
        self.txtVales2.setObjectName("txtVales2")
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setGeometry(QtCore.QRect(430, 210, 381, 91))
        self.label_28.setStyleSheet("background-color:none;\n"
"font-size:14pt;")
        self.label_28.setObjectName("label_28")
        self.lblRespostaValeT = QtWidgets.QLabel(self.page_5)
        self.lblRespostaValeT.setGeometry(QtCore.QRect(420, 370, 111, 61))
        self.lblRespostaValeT.setStyleSheet("background-color: none;\n"
"font-size:14pt;")
        self.lblRespostaValeT.setText("")
        self.lblRespostaValeT.setObjectName("lblRespostaValeT")
        self.lblRespostaValeA = QtWidgets.QLabel(self.page_5)
        self.lblRespostaValeA.setGeometry(QtCore.QRect(680, 370, 111, 61))
        self.lblRespostaValeA.setStyleSheet("background-color: none;\n"
"font-size:14pt;")
        self.lblRespostaValeA.setObjectName("lblRespostaValeA")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(680, 320, 111, 31))
        self.label_7.setStyleSheet("font-size:14pt;\n"
"background-color: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setGeometry(QtCore.QRect(420, 320, 91, 31))
        self.label_8.setStyleSheet("font-size:14pt;\n"
"background-color: none;")
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 831, 441))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagens/Apresentação Divertida Adivinhe a Imagem Ampliada Jogo Simples Limpo Digital Amarelo e Laranja.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnInstagram = QtWidgets.QPushButton(self.page_6)
        self.btnInstagram.setGeometry(QtCore.QRect(20, 400, 41, 41))
        self.btnInstagram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInstagram.setStyleSheet("background-color: white;")
        self.btnInstagram.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Instagram_icon-icons.com_66804.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInstagram.setIcon(icon1)
        self.btnInstagram.setIconSize(QtCore.QSize(40, 40))
        self.btnInstagram.setObjectName("btnInstagram")
        self.btnFacebook = QtWidgets.QPushButton(self.page_6)
        self.btnFacebook.setGeometry(QtCore.QRect(80, 400, 41, 41))
        self.btnFacebook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFacebook.setStyleSheet("background-color:none;")
        self.btnFacebook.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/fb_icon-icons.com_65434.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFacebook.setIcon(icon2)
        self.btnFacebook.setIconSize(QtCore.QSize(40, 35))
        self.btnFacebook.setObjectName("btnFacebook")
        self.BtnSite = QtWidgets.QPushButton(self.page_6)
        self.BtnSite.setGeometry(QtCore.QRect(140, 400, 41, 41))
        self.BtnSite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSite.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BtnSite.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagens/Twitter_icon-icons.com_66803.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnSite.setIcon(icon3)
        self.BtnSite.setIconSize(QtCore.QSize(25, 25))
        self.BtnSite.setObjectName("BtnSite")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(670, 350, 141, 71))
        self.label_10.setStyleSheet("background-color: none;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("imagens/images-removebg-preview (1).png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_6)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", " Serviço Nacional de Aprendizagem Comercial"))
        self.pushButton.setText(_translate("Dialog", "Home"))
        self.pushButton_2.setText(_translate("Dialog", "Holerite"))
        self.pushButton_3.setText(_translate("Dialog", "INSS"))
        self.pushButton_4.setText(_translate("Dialog", "IRRF"))
        self.pushButton_5.setText(_translate("Dialog", "Vales"))
        self.pushButton_6.setText(_translate("Dialog", "Sobre"))
        self.groupBox_5.setTitle(_translate("Dialog", "Conifgurações:"))
        self.txtValorBruto.setPlaceholderText(_translate("Dialog", "Digite aqui o valor bruto"))
        self.btnPdf.setText(_translate("Dialog", "Gerar pdf"))
        self.btnExcell.setText(_translate("Dialog", "Excell"))
        self.btnCalcular.setText(_translate("Dialog", "Operação"))
        self.txtNome.setPlaceholderText(_translate("Dialog", "Digite seu nome"))
        self.txtCargo.setPlaceholderText(_translate("Dialog", "Digite seu cargo"))
        self.btnNovo.setText(_translate("Dialog", "Novo"))
        self.label_6.setText(_translate("Dialog", "Valor Líquido:"))
        self.groupBox_4.setTitle(_translate("Dialog", "Cálculo:"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">INSS</p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">FGTS</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">IRRF</p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Vale Transporte:</p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Vale Alimentação:</p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#000000;\">INSS</span></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "O valor que será cobrado do total inserido é:"))
        self.lblRespostaINSS.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">IRRF</span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "O valor que será cobrado do total inserido é:"))
        self.lblRespostaIRRF.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Vales</span></p></body></html>"))
        self.label_28.setText(_translate("Dialog", "O valor que será cobrado do total inserido é:"))
        self.lblRespostaValeA.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Alimentação"))
        self.label_8.setText(_translate("Dialog", "Transporte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
